blog/web/auth.py
from flask import Blueprint, flash, render_template,redirect,url_for,request
from .import db
from .models import User,Post
from flask_login import current_user, login_user,logout_user,login_required
from werkzeug.security import generate_password_hash,check_password_hash
auth=Blueprint("auth",__name__)

@auth.route('/login',methods=['GET','POST'])
def login():
    if request.method=='POST':
        email=request.form.get("email")
        password=request.form.get("pswd")
        user=User.query.filter_by(email=email).first()
        if user:
            print(user.email)
            print(password)
            print(user.password)
            if check_password_hash(user.password,password):
                flash("Logged In!",category='success')
                login_user(user,remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('password is incorrect',category='error')
        else:
            flash('EMail does not exist',category='error')
    return render_template('login.html',user=current_user)

@auth.route('/sign-up', methods=['GET','POST'])
def sign_up():
    if request.method=='POST':
        email=request.form.get("email")
        username=request.form.get("username")
        password1=request.form.get("password1")
        password2=request.form.get("password2")
        email_exists=User.query.filter_by(email=email).first()
        user_exists=User.query.filter_by(username=username).first()
        if email_exists:
            flash('Email is already is use.',category='error')
        elif user_exists:
            flash('Username is already exists.',category='error')
        elif password1 != password2:
            print(password1)
            print(password2)
            flash('password is not matching',category='error')
        elif len(username)<3:
             flash('Username is too short',category='error')
        elif len(password1)<3:
             flash('password is too short',category='error')
        else:
            new_user=User(email=email,username=username,password=generate_password_hash(password1,method="sha256"))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user,remember=True)
            flash('user created')
            return redirect(url_for('views.home'))
    return render_template('sign_up.html',user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.home'))

blog/web/views.py

from crypt import methods
from sre_constants import CATEGORY
from unicodedata import category
from flask import Blueprint, redirect, render_template,request,flash,url_for
views=Blueprint('views',__name__)
from flask_login import login_required,current_user
from .models import Post,User,Comments,Likes
from .models import db
@views.route('/home')
@views.route('/')

@login_required
def home():
    post=Post.query.all()
    return render_template('home.html',user=current_user,posts=post)

@views.route('/search',methods=["post"])
def search():
    text1=request.form.get('searched')
    posts=posts.filter(Post.posts.like('%'+ text1 + '%'))
    return render_template('ntg.html',searched=text1,posts=posts)

@views.route('/create_post',methods=['GET','POST'])
@login_required
def  create_post():
    if request.methods=="POST":
        text=request.form.get('post_text')
        if not text:
            flash('Post can not be empty',category="error")
        else:
            post=Post(post_text=text,author=current_user.id)
            db.session.add(post)
            db.session.commit()
            flash('post create',category="success")
    return render_template('create_post.html',user=current_user)

#for delete a post
@views.route("/delete_post/<id>")
@login_required
def delete_post(id):
    post=Post.query.filter_by(id=id).first()
    if not post:
        flash("flash does not exist",category="error")
    elif current_user.id !=post.id:
        flash("You are not right person to delete this messages",category="error")
    else:
        db.session.delete(post)
        db.session.commit()
        flash("Post Deleted",category="success")
    return redirect(url_for('views.home'))
# for specific user post to display
@views.route("/post/<username>")
@login_required
def posts(username):
    user=User.query.filter_by(username=username).first()
    if not user:
        flash("no User with that username exist .",category="error")
        return redirect(url_for('views.home'))
    posts=user.posts
    return render_template("posts.html",user=current_user,posts=posts,username=username)

#create comments
@views.route('/create_comment/<post_id>',methods=['POST'])
@login_required
def create_comment(post_id):
    cmnt=request.form.get('commnet_text')
    if not cmnt:
        flash("Null comment is not Acceptable here",category="error")
    else:
        post=Post.query.filter_by(id=post_id)
        if post:
            comment=Comments(cm_text=cmnt,author=current_user.id,post_id=post_id)
            db.session.add(comment)
            db.session.commit()
        else:
            flash('Post does not exist',category="error")
    return redirect(url_for('views.home'))

#delete commentss

@views.route("/delete_comment/<cm_id>")
@login_required
def delete_comm(cm_id):
    comm=Comments.query.filter_by(id=cm_id).first()
    if not comm:
        flash("flash does not exist",category="error")
    elif current_user.id !=comm.author and current_user.id!=comm.post.author:
        flash("You are not right person to delete this messages",category="error")
    else:
        db.session.delete(comm)
        db.session.commit()
        flash("Comment Deleted",category="success")
    return redirect(url_for('views.home'))

#like button to display the like
@views.route("/like_post/<post_id>",methods=['GET'])
@login_required
def like_post(post_id):
    post=Post.query.filter_by(id=post_id)
    like=Likes.query.filter_by(author=current_user.id,post_id=post_id).first()
    if not post:
        flash("post does not exist",category="error")
    elif like:
        print("it is working")
        db.session.delete(like)
        db.session.commit()
    else:
        like=Likes(author=current_user.id,post_id=post_id)
        db.session.add(like)
        db.session.commit()
    return redirect(url_for('views.home'))

blog/web/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a8530e2e11.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="base.css"> 
    <title>
        {% block title %}

        {% endblock %}
    </title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:rgb(5, 0, 22);">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link " href="{{url_for('views.home')}}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('auth.logout')}}">Loguout</a>
              </li>
              
              {% else %}
              <li class="nav-item">
                <a class="nav-link " href="{{url_for('views.home')}}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('auth.login')}}">LOGIN</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('auth.sign_up')}}">SIGNUP</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
      {% with messages=get_flashed_messages(with_categories=True)%}
        {% if messages %}
          {% for category,message in messages %}
          {% if category=="error"%}
              <div class="alert alert-danger alert-dismissible fade show" role="alert">
               {{message}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
               <span aria-hidden="true">&times;</span>
                </button>
              </div>
          {% else %}
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{message}}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
          {% endif %}        
          
          {% endfor %}
        {%endif%}
      {% endwith %}
    <div class="container">
    {% block content%}
      
    {% endblock %}
    </div>
    <!-- JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{{url_for('static',filename='index.js')}}"></script>
  </body>
</html>

blog/web/templates/create_post.html
{% extends 'base.html'%}

{% block title%}
create post
{% endblock%}
{% block content%}
<h1>create a posts</h1>
<form method="POST">
    <textarea name="post_text" id="post_text" class="form-control"></textarea>
    <b{% extends 'base.html'%}

    {% block title%}
    login
    {% endblock%}
    {% block content%}
        <h2>login form</h2>
        <form method="POST">
            <div class="form-outline mb-4">
              <input type="email" name="email" id="form2Example1" class="form-control" />
              <label class="form-label" for="form2Example1">Email address</label>
            </div>
            <div class="form-outline mb-4">
              <input type="password" name="pswd" id="form2Example2" class="form-control" />
              <label class="form-label" for="form2Example2">Password</label>
            </div>
            <div class="row mb-4">      
              <div class="col">
                <a href="#!">Forgot password?</a>
              </div>
            </div>
            <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>
          </form>
    {% endblock %}r>
    <button type="submit" class="btn btn-lg btn-primary">Post</button>
</form>
{% endblock %}

blog/web/templates/dup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

blog/web/templates/home.html

{% extends 'post_div.html' %}
{% block title%}home{% endblock%}
{% block header %}Post's{% endblock %}

blog/web/templates/login.html
{% extends 'base.html'%}

{% block title%}
login
{% endblock%}
{% block content%}
    <h2>login form</h2>
    <form method="POST">
        <div class="form-outline mb-4">
          <input typhttp://127.0.0.1:5000/sign-upe="email" name="email" id="form2Example1" class="form-control" />
          <label class="form-label" for="form2Example1">Email address</label>
        </div>
        <div class="form-outline mb-4">
          <input type="password" name="pswd" id="form2Example2" class="form-control" />
          <label class="form-label" for="form2Example2">Password</label>
        </div>
        <div class="row mb-4">      
          <div class="col">
            <a href="#!">Forgot password?</a>
          </div>
        </div>
        <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>
      </form>
{% endblock %}

blog/web/templates/post_div.html
{% extends 'base.html'%}

{% block title%}
home
{% endblock%}
{% block content%}
<h1 align="center">{%block header%}{{username}}'s Posts{%endblock%}</h1>
<div id="posts">
{% for post in posts%}
<div class="border border-top-0 border-primary rounded">
<div class="alert alert-primary" role="alert">
    <a href="/post/{{post.user.username}}">{{post.user.username}}</a> {{post.post_text}}
    {% if user.id==post.author %}
    <div class="btn-group">
    <button type="button" class="btn btn-sm btn-primary dropdown-toggle" data-bs-toggle="dropdown"></button>
    <ul class="dropdown-menu">
        <li>
            <a href="/delete_post/{{post.id}}" class="dropdown-item">Delete</a>
        </li>
    </ul>
    </div>
    {% endif %}
</div>
<div>
    <div class="collapse"id="comments-expanded-{{post.id}}">
    {% for comment in post.comments %}
    <div class="d-flex justify-content-between align-items-center">
    <p class="text-dark">&emsp;&emsp;{{comment.cm_text}}</p>
    <small class="text-muted">{{comment.date_created}}</small>
    {% if user.id==comment.author or user.id== post.author %}
    <div class="btn-group">
        <i class="material-icons btn btn-sm btn-primary dropdown-toggle" data-bs-toggle="dropdown">&#xe872;</i>
        <ul class="dropdown-menu">
            <li>
                <a href="/delete_comment/{{comment.id}}" class="dropdown-item">Delete</a>
            </li>
        </ul>
        </div>
    {% endif %}
    </div>
    {% endfor %}
    </div>
    {% if post.comments|length >0 %}
    <a data-bs-toggle="collapse" href="#comments-expanded-{{post.id}}" role="button">
        <small class="m-3">View {{post.comments|length}} Comments</small>
    </a>
    {% else %}
    <small class="text-muted m-3">No comments</small>
    {% endif%}

<div class="makecomment">
    <form class="input-group mb-3" method="POST" action="/create_comment/{{post.id}}">
        <input type="text" id="text" name="commnet_text" class="form-control" placeholder="comment here....!" style="border-bottom:1px solid blue;border-color:transparent;overflow:auto;"/>
        <button type="submit" class="btn btn-primary">Comment</button>
    </form>
    
</div>
</div>
<!-- {%set liked=false %}
{%for Like in post.likes %}
    {% if Like.author==current_user.id %}
        {% set liked=true %}
    {% endif %}
{% endfor %}
heart comments
{% if liked%}
    {%  set icon_name="fas fa-heart" %}
{% else %}
{%  set icon_name="far fa-heart" %}
{% endif %} -->
<div class="d-flex m-3 justify-content-between bg-light rounded">
   <!--{{post.likes|length}}-->
     {% if user.id in post.likes|map(attribute="author")|list %}
     <a href="/like_post/{{post.id}}"><i class="fas fa-heart"> {{post.likes|length}}</i></a>
    <!--- <i class="fas fa-heart" id="like-button-{{post.id}}" onclick="like({{post.id}})"></i>-->
     {% else %} 
     <a href="/like_post/{{post.id}}"><i class="far fa-heart"> {{post.likes|length}}</i></a>
     <!--- <i class="far fa-heart" id="like-button-{{post.id}}" onclick="like({{post.id}})"></i>-->
     {% endif %}
    <!-- <a href="/like_post/{{post.id}}">
        <i class="{{icon_name}}"> {{post.likes|length}}</i>
    </a>-->
    {{post.date_created}}</div> 
</div>
<br>
{% endfor %}
</div>
{%block footer%}
    <div align="center">
        <a href="{{url_for('views.create_post')}}"><button type="button" class="btn btn-lg btn-primary">Create Post</button></a>
    </div>
    {% endblock %}
{% endblock %}

blog/web/templates/posts.html
{% extends 'post_div.html'%}

{% block title%}{{username}}'s Posts{% endblock%}
{% block header %}{{username}}'s Posts {% endblock %}

blog/web/templates/search.html
{% extends 'base.html'%}

{% block title%}
search
{% endblock%}
{% block content%}
<form method="post" action="{{ url_for('search')}}" class="d-flex">
  <input class="form-controlme-2" type="seach" placeholder="Search.." name="searched">
  <button class="btn" type="submit">search<i class="fa fa-search"></i></button>
</form>
{% endblock %}

<!-- <form action="/search">
        <input autocomplete="off" autofocus id="srch" name="srch" placeholder="Enter Text....">
        <input type="submit">
    </form> -->

blog/web/templates/sign_up.html
{% extends 'base.html'%}

{% block title%}
sign_up
{% endblock%}
{% block content%}
<h1>
REGISTER HERE
</h1>
<form method="POST">
    <div class="form-outline mb-4">
        <label class="form-label" for="em1">Email address</label>
      <input type="email"  name ="email"id="em1" class="form-control" />
      
    </div>
    <div class="form-outline mb-4">
        <label class="form-label" for="u1">Username</label>
        <input type="text" name="username" id="u1" class="form-control" />
        
      </div>
    <div class="form-outline mb-4">
      <label class="form-label" for="p1">Password</label>
      <input type="password" name="password1" id="p1" class="form-control" />
      
    </div>
    <div class="form-outline mb-4">
        <label class="form-label" for="pa1">Confirm Password</label>
        <input type="password" name="password2" id="pa1" class="form-control" />
       
      </div>
    <div class="row mb-4">      
      <div class="col">
      If you already registered  <a href="{{url_for('auth.login')}}">login here</a>
      </div>
    </div>
    <button type="submit" class="btn btn-primary btn-block mb-4">Sign-Up</button>
  </form>
{% endblock %}